class Book:
    """A book that is part of the library"""
    def __init__(self, title, author, pages, cover, published_date, description, isbn, amount, id):
        """Create a new book instance
        
        A book can belong in multiple genres

        title           the title of the book (eg. Peter Pan)
        genres          a list containing the genres of a book (eg. Fantasy, Science Fiction)
        author          the book's author (eg. J. M. Barrie)
        pages           the amount of pages (eg. 234)
        cover           contains a link to the book's cover
        published_date  the book's publication date (eg. 2004)
        description     a short sentence describing the book
        isbn            book's unique identifier provided by publisher (ISBN-13 only)
        amount          the amount of copies that exist in the library
        id              unique identification code generated by the library system (eg. B1)
        """
        self.title = title
        self.genres = []
        self.author = author
        self.pages = pages
        self.cover = cover
        self.published_date = published_date
        self.description = description
        self.isbn = isbn
        self.amount = amount
        self.id = id
    
    def add_new_genre(self, genre):
        """ Adds a new genre to the list of an existing book """
        self.genres.append(genre)

    def borrow_book(self):
        """ Reduces the amount of copies when a book is borrowed 
            if there are zero copies it returns False"""
        if self.amount > 0:
            self.amount -= 1
            return True
        return False
    
    def return_book(self):
        """ When a book is returned it increases the amount of available copies"""
        self.amount += 1
    
    def increase_copies(self, amount):
        """ Increases the amount of copies"""
        self.amount += amount

    def __str__(self):
        return f'{self.title} by {self.author} publication date: {self.published_date}, pages: {self.pages},\n{self.genres}, description: {self.description} isbn: {self.isbn}, amount in inventory: {self.amount}, id: {self.id}'